[package]
name = "bin_literals_macros"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]

[dependencies]
bin = { path = "../", version = "0.1" }
procedural-masquerade = "0.1"

[lib]
proc-macro = true
