[package]
name = "bin_literals"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]

[dependencies]
bin_literals_macros = { path = "../bin_literals_macros", version = "0.1" }
procedural-masquerade = "0.1"

[dev-dependencies]
bin = { path = "../", version = "0.1" }
